### ISSUE TITLE
Allow a regexp to be matched

### ISSUE THREAD

**Issue by adityacs** [stvp/go-udp-testing#5]
I have a use case where my expected string is 
`requests.total,code=200,method=GET,service=test count=1 [0-9]{19}\n`

If I call udp.ShouldReceiveAll, I will get 
`requests.total,code=200,method=GET,service=test count=1 12340000\n`

the last part `[0-9]{19}` is a nanosecond timestamp. 

Is there a way to handle this now?

I am expecting something like here
 https://github.com/go-kit/kit/blob/master/metrics/influx/example_test.go#L23-L26

**Comment by adityacs** [comment]
@tysonmote @n1koo Could you please help with this?

**Comment by tysonmote** [comment]
#6 addresses this. If I'm mistaken, feel free to re-open!
